# ============================================================
# CBAM U-NET TRAINING FOR MARTIAN DUST STORM SEGMENTATION
# Article-style pipeline for MDGM/MDAD selected_top100 folders.
#
# Main choices following the guide article:
# - Per-year split: 70% train, 15% validation, 15% test.
# - Patch size: 668 x 688 x 3.
# - Sliding window step: 334 px, i.e., ~50% overlap.
# - U-Net with CBAM modules in skip connections.
# - Weighted BCE with pos_weight = 23.
# - Threshold selected from validation by maximizing IoU.
# - Final test evaluation + visualization of 5 test patches.
#
# Expected input structure generated by codigo_mdgm_mdad_pairing_v2.py:
# ROOT/
# ├── MY28/reports/selected_top100.csv
# ├── MY31/reports/selected_top100.csv
# └── MY32/reports/selected_top100.csv
#
# Mask convention: 0=no storm, 1=storm, 2=no-data / invalid pixel
# ============================================================

from __future__ import annotations

import random
from functools import lru_cache
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

from PIL import Image
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

# ============================================================
# 1. CONFIGURATION
# ============================================================

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

ROOT_DIR = Path(__file__).resolve().parent
YEARS = ["MY28", "MY31", "MY32"]

TRAIN_FRAC = 0.70
VAL_FRAC = 0.15
TEST_FRAC = 0.15

PATCH_H = 668
PATCH_W = 688
STRIDE = 334
WRAP_PAD_X = 36

BLACK_THRESHOLD = 5
BORDER_BLACK_FRAC = 0.95
MIN_VALID_RATIO = 0.50

BASE_CHANNELS = 16
POS_WEIGHT = 23.0
LEARNING_RATE = 1e-4
BATCH_SIZE = 12          # Article used 16; use 2/4 on laptop GPU, increase if VRAM allows.
NUM_EPOCHS = 15
NUM_WORKERS = 4
USE_AMP = True

THRESHOLD_MIN = 0.500
THRESHOLD_MAX = 0.999
THRESHOLD_STEP = 0.001

N_TEST_VISUALIZATIONS = 5

OUTPUT_DIR = ROOT_DIR / "cbam_unet_article_style_outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BEST_MODEL_PATH = OUTPUT_DIR / "best_cbam_unet_mdad_article_style.pth"
HISTORY_CSV = OUTPUT_DIR / "training_history.csv"
SPLIT_CSV = OUTPUT_DIR / "image_split_manifest.csv"
PATCH_CSV = OUTPUT_DIR / "patch_inventory_all_splits.csv"
VAL_THRESHOLD_CSV = OUTPUT_DIR / "validation_threshold_sweep.csv"
TEST_METRICS_CSV = OUTPUT_DIR / "test_metrics.csv"
TEST_VIS_FIG = OUTPUT_DIR / "test_5_patch_predictions.png"
CONFUSION_MATRIX_FIG = OUTPUT_DIR / "test_confusion_matrix.png"

# ============================================================
# 2. DEVICE
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if device.type == "cuda":
    torch.backends.cudnn.benchmark = True
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")

# ============================================================
# 3. FILE PAIRING AND SPLIT
# ============================================================

def read_rgb(path: Path) -> np.ndarray:
    with Image.open(path) as img:
        return np.asarray(img.convert("RGB"))


def read_mask(path: Path) -> np.ndarray:
    with Image.open(path) as img:
        return np.asarray(img.convert("L")).astype(np.uint8)


def find_mask_for_image(mask_dir: Path, image_path: Path) -> Path:
    stem = image_path.stem
    direct = mask_dir / f"{stem}_mask_class.png"
    if direct.exists():
        return direct
    candidates = sorted(mask_dir.glob(f"{stem}*mask*.png"))
    if candidates:
        return candidates[0]
    candidates = sorted(mask_dir.glob(f"*{stem}*.png"))
    if candidates:
        return candidates[0]
    raise FileNotFoundError(f"No mask found for image: {image_path}")


def load_year_records(year: str) -> pd.DataFrame:
    year_dir = ROOT_DIR / year
    report_csv = year_dir / "reports" / "selected_top100.csv"
    rows = []

    if report_csv.exists():
        df = pd.read_csv(report_csv).copy()
        for _, row in df.iterrows():
            image_path = ROOT_DIR / str(row["image_path"])
            mask_path = ROOT_DIR / str(row["mask_png_path"])

            if not image_path.exists():
                alt = year_dir / "selected_top100" / "images" / image_path.name
                image_path = alt if alt.exists() else image_path
            if not mask_path.exists():
                alt = year_dir / "selected_top100" / "masks" / mask_path.name
                mask_path = alt if alt.exists() else mask_path

            if image_path.exists() and mask_path.exists():
                rows.append({
                    "year": year,
                    "idx": int(row["idx"]) if "idx" in row and not pd.isna(row["idx"]) else len(rows),
                    "day_key": str(row["day_key"]) if "day_key" in row else image_path.stem,
                    "image_path": str(image_path),
                    "mask_path": str(mask_path),
                    "storm_pct_valid": float(row["storm_pct_valid"]) if "storm_pct_valid" in row else np.nan,
                })
    else:
        image_dir = year_dir / "selected_top100" / "images"
        mask_dir = year_dir / "selected_top100" / "masks"
        image_paths = []
        for ext in ["*.png", "*.jpg", "*.jpeg", "*.tif", "*.tiff"]:
            image_paths.extend(sorted(image_dir.glob(ext)))
        for i, image_path in enumerate(sorted(image_paths)):
            mask_path = find_mask_for_image(mask_dir, image_path)
            rows.append({
                "year": year,
                "idx": i,
                "day_key": image_path.stem,
                "image_path": str(image_path),
                "mask_path": str(mask_path),
                "storm_pct_valid": np.nan,
            })

    out = pd.DataFrame(rows)
    if out.empty:
        raise RuntimeError(f"No image-mask pairs found for {year}.")

    # Keep the same selected top-100 set, but sort by MDAD time index before splitting.
    out = out.sort_values("idx").head(100).reset_index(drop=True)
    print(f"{year}: loaded {len(out)} selected image-mask pairs.")
    return out


def split_records_per_year(records_by_year: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    split_rows = []
    for year, df in records_by_year.items():
        df = df.sort_values("idx").reset_index(drop=True)
        n = len(df)
        n_train = int(round(n * TRAIN_FRAC))
        n_val = int(round(n * VAL_FRAC))
        n_test = n - n_train - n_val

        df = df.copy()
        df["split"] = ["train"] * n_train + ["val"] * n_val + ["test"] * n_test
        split_rows.append(df)
        print(f"{year}: train={n_train}, val={n_val}, test={n_test}, total={n}")

    split_df = pd.concat(split_rows, ignore_index=True)
    split_df.to_csv(SPLIT_CSV, index=False)
    print(f"Image split manifest saved to: {SPLIT_CSV}")
    return split_df

# ============================================================
# 4. PREPROCESSING AND PATCH INVENTORY
# ============================================================

def detect_black(rgb: np.ndarray) -> np.ndarray:
    return np.all(rgb <= BLACK_THRESHOLD, axis=2)


def trim_black_borders(rgb: np.ndarray, mask: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    black = detect_black(rgb)
    h, w = black.shape

    top = 0
    while top < h - 1 and black[top, :].mean() >= BORDER_BLACK_FRAC:
        top += 1

    bottom = h - 1
    while bottom > top and black[bottom, :].mean() >= BORDER_BLACK_FRAC:
        bottom -= 1

    left = 0
    while left < w - 1 and black[:, left].mean() >= BORDER_BLACK_FRAC:
        left += 1

    right = w - 1
    while right > left and black[:, right].mean() >= BORDER_BLACK_FRAC:
        right -= 1

    return rgb[top:bottom + 1, left:right + 1], mask[top:bottom + 1, left:right + 1]


def wrap_pad_east_west(rgb: np.ndarray, mask: np.ndarray, pad: int = WRAP_PAD_X) -> Tuple[np.ndarray, np.ndarray]:
    if pad <= 0 or mask.shape[1] <= 2 * pad:
        return rgb, mask
    rgb_padded = np.concatenate([rgb[:, -pad:, :], rgb, rgb[:, :pad, :]], axis=1)
    mask_padded = np.concatenate([mask[:, -pad:], mask, mask[:, :pad]], axis=1)
    return rgb_padded, mask_padded


def preprocess_pair(rgb: np.ndarray, mask: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    if rgb.shape[:2] != mask.shape:
        raise ValueError(f"RGB and mask shapes do not match: rgb={rgb.shape}, mask={mask.shape}")

    mask = mask.copy()
    mask[detect_black(rgb)] = 2
    rgb, mask = trim_black_borders(rgb, mask)
    mask[detect_black(rgb)] = 2
    rgb, mask = wrap_pad_east_west(rgb, mask, WRAP_PAD_X)
    return rgb, mask


@lru_cache(maxsize=24)
def load_preprocessed_pair_cached(image_path_str: str, mask_path_str: str) -> Tuple[np.ndarray, np.ndarray]:
    rgb = read_rgb(Path(image_path_str))
    mask = read_mask(Path(mask_path_str))
    return preprocess_pair(rgb, mask)


def build_patch_inventory(split_df: pd.DataFrame) -> pd.DataFrame:
    patch_rows = []

    for _, row in tqdm(split_df.iterrows(), total=len(split_df), desc="Building patch inventory"):
        rgb, mask = load_preprocessed_pair_cached(str(row["image_path"]), str(row["mask_path"]))
        h, w = mask.shape
        if h < PATCH_H or w < PATCH_W:
            continue

        for y0 in range(0, h - PATCH_H + 1, STRIDE):
            for x0 in range(0, w - PATCH_W + 1, STRIDE):
                y1, x1 = y0 + PATCH_H, x0 + PATCH_W
                mask_patch = mask[y0:y1, x0:x1]
                valid = mask_patch != 2
                valid_ratio = float(valid.mean())

                # Article criterion: discard if black/no-data pixels are more than informative pixels.
                if valid_ratio <= MIN_VALID_RATIO:
                    continue

                storm_ratio_valid = float(np.mean(mask_patch[valid] == 1)) if valid.any() else 0.0
                storm_pixels = int((mask_patch == 1).sum())

                patch_rows.append({
                    "year": row["year"],
                    "idx": row["idx"],
                    "day_key": row["day_key"],
                    "split": row["split"],
                    "image_path": str(row["image_path"]),
                    "mask_path": str(row["mask_path"]),
                    "x0": x0,
                    "y0": y0,
                    "x1": x1,
                    "y1": y1,
                    "valid_ratio": valid_ratio,
                    "storm_ratio_valid": storm_ratio_valid,
                    "storm_pixels": storm_pixels,
                    "positive_patch": storm_pixels > 0,
                })

    inv = pd.DataFrame(patch_rows)
    if inv.empty:
        raise RuntimeError("No patches were generated. Check paths and patch parameters.")

    inv.to_csv(PATCH_CSV, index=False)
    print(f"Patch inventory saved to: {PATCH_CSV}")
    print("Patch count by split:")
    print(inv["split"].value_counts())
    print("Positive patch fraction by split:")
    print(inv.groupby("split")["positive_patch"].mean())
    return inv

# ============================================================
# 5. DATASET AND NORMALIZATION
# ============================================================

class MDGMPatchDataset(Dataset):
    def __init__(self, patch_inventory: pd.DataFrame, mean: np.ndarray, std: np.ndarray, augment_4x: bool = False):
        self.inv = patch_inventory.reset_index(drop=True)
        self.mean = mean.astype(np.float32)
        self.std = std.astype(np.float32)
        self.augment_4x = augment_4x
        self.multiplier = 4 if augment_4x else 1

    def __len__(self):
        return len(self.inv) * self.multiplier

    def __getitem__(self, index):
        base_index = index % len(self.inv)
        aug_id = index // len(self.inv) if self.augment_4x else 0
        row = self.inv.iloc[base_index]

        rgb, mask = load_preprocessed_pair_cached(row["image_path"], row["mask_path"])
        x0, y0, x1, y1 = int(row["x0"]), int(row["y0"]), int(row["x1"]), int(row["y1"])

        img_patch = rgb[y0:y1, x0:x1].astype(np.float32) / 255.0
        mask_patch = mask[y0:y1, x0:x1].astype(np.uint8)

        target = (mask_patch == 1).astype(np.float32)
        valid = (mask_patch != 2).astype(np.float32)

        if aug_id == 1:
            img_patch = np.flip(img_patch, axis=1).copy()
            target = np.flip(target, axis=1).copy()
            valid = np.flip(valid, axis=1).copy()
        elif aug_id == 2:
            img_patch = np.flip(img_patch, axis=0).copy()
            target = np.flip(target, axis=0).copy()
            valid = np.flip(valid, axis=0).copy()
        elif aug_id == 3:
            img_patch = np.flip(np.flip(img_patch, axis=0), axis=1).copy()
            target = np.flip(np.flip(target, axis=0), axis=1).copy()
            valid = np.flip(np.flip(valid, axis=0), axis=1).copy()

        img_patch = (img_patch - self.mean) / (self.std + 1e-8)
        img_patch = np.transpose(img_patch, (2, 0, 1))
        target = target[None, :, :]
        valid = valid[None, :, :]

        return (
            torch.tensor(img_patch, dtype=torch.float32),
            torch.tensor(target, dtype=torch.float32),
            torch.tensor(valid, dtype=torch.float32),
        )


def compute_train_mean_std(train_image_df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
    total_sum = np.zeros(3, dtype=np.float64)
    total_sq = np.zeros(3, dtype=np.float64)
    total_n = 0

    for _, row in tqdm(train_image_df.iterrows(), total=len(train_image_df), desc="Computing train mean/std"):
        rgb, mask = load_preprocessed_pair_cached(str(row["image_path"]), str(row["mask_path"]))
        valid = mask != 2
        pixels = rgb[valid].astype(np.float32) / 255.0
        if pixels.size == 0:
            continue
        total_sum += pixels.sum(axis=0)
        total_sq += (pixels ** 2).sum(axis=0)
        total_n += pixels.shape[0]

    if total_n == 0:
        raise RuntimeError("No valid pixels found for normalization.")

    mean = total_sum / total_n
    var = total_sq / total_n - mean ** 2
    std = np.sqrt(np.maximum(var, 1e-8))
    return mean.astype(np.float32), std.astype(np.float32)

# ============================================================
# 6. CBAM U-NET
# ============================================================

class ConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.LeakyReLU(negative_slope=0.01, inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.LeakyReLU(negative_slope=0.01, inplace=True),
        )

    def forward(self, x):
        return self.block(x)


class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        hidden = max(channels // reduction, 1)
        self.mlp = nn.Sequential(
            nn.Conv2d(channels, hidden, kernel_size=1, bias=False),
            nn.LeakyReLU(negative_slope=0.01, inplace=True),
            nn.Conv2d(hidden, channels, kernel_size=1, bias=False),
        )

    def forward(self, x):
        avg_pool = F.adaptive_avg_pool2d(x, 1)
        max_pool = F.adaptive_max_pool2d(x, 1)
        attention = torch.sigmoid(self.mlp(avg_pool) + self.mlp(max_pool))
        return x * attention


class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        padding = kernel_size // 2
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=padding, bias=False)

    def forward(self, x):
        avg_map = torch.mean(x, dim=1, keepdim=True)
        max_map, _ = torch.max(x, dim=1, keepdim=True)
        attention = torch.sigmoid(self.conv(torch.cat([avg_map, max_map], dim=1)))
        return x * attention


class CBAM(nn.Module):
    def __init__(self, channels, reduction=16, spatial_kernel=7):
        super().__init__()
        self.channel_attention = ChannelAttention(channels, reduction=reduction)
        self.spatial_attention = SpatialAttention(kernel_size=spatial_kernel)

    def forward(self, x):
        return self.spatial_attention(self.channel_attention(x))


class CBAMUNet(nn.Module):
    def __init__(self, in_channels=3, out_channels=1, base_channels=16):
        super().__init__()
        f1, f2, f3, f4, f5 = base_channels, base_channels * 2, base_channels * 4, base_channels * 8, base_channels * 16
        self.pool = nn.MaxPool2d(2, 2)

        self.enc1 = ConvBlock(in_channels, f1)
        self.enc2 = ConvBlock(f1, f2)
        self.enc3 = ConvBlock(f2, f3)
        self.enc4 = ConvBlock(f3, f4)
        self.bottleneck = ConvBlock(f4, f5)

        self.cbam1 = CBAM(f1)
        self.cbam2 = CBAM(f2)
        self.cbam3 = CBAM(f3)
        self.cbam4 = CBAM(f4)

        self.up4_conv = nn.Conv2d(f5, f4, kernel_size=1)
        self.dec4 = ConvBlock(f4 + f4, f4)
        self.up3_conv = nn.Conv2d(f4, f3, kernel_size=1)
        self.dec3 = ConvBlock(f3 + f3, f3)
        self.up2_conv = nn.Conv2d(f3, f2, kernel_size=1)
        self.dec2 = ConvBlock(f2 + f2, f2)
        self.up1_conv = nn.Conv2d(f2, f1, kernel_size=1)
        self.dec1 = ConvBlock(f1 + f1, f1)
        self.final = nn.Conv2d(f1, out_channels, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        e4 = self.enc4(self.pool(e3))
        b = self.bottleneck(self.pool(e4))

        d4 = F.interpolate(b, size=e4.shape[2:], mode="bilinear", align_corners=False)
        d4 = self.up4_conv(d4)
        d4 = self.dec4(torch.cat([d4, self.cbam4(e4)], dim=1))

        d3 = F.interpolate(d4, size=e3.shape[2:], mode="bilinear", align_corners=False)
        d3 = self.up3_conv(d3)
        d3 = self.dec3(torch.cat([d3, self.cbam3(e3)], dim=1))

        d2 = F.interpolate(d3, size=e2.shape[2:], mode="bilinear", align_corners=False)
        d2 = self.up2_conv(d2)
        d2 = self.dec2(torch.cat([d2, self.cbam2(e2)], dim=1))

        d1 = F.interpolate(d2, size=e1.shape[2:], mode="bilinear", align_corners=False)
        d1 = self.up1_conv(d1)
        d1 = self.dec1(torch.cat([d1, self.cbam1(e1)], dim=1))

        return self.final(d1)

# ============================================================
# 7. LOSS AND METRICS
# ============================================================

class MaskedWeightedBCELoss(nn.Module):
    def __init__(self, pos_weight=23.0):
        super().__init__()
        self.register_buffer("pos_weight", torch.tensor([pos_weight], dtype=torch.float32))

    def forward(self, logits, targets, valid):
        loss = F.binary_cross_entropy_with_logits(logits, targets, pos_weight=self.pos_weight, reduction="none")
        return (loss * valid).sum() / (valid.sum() + 1e-8)


def counts_to_metrics(tp, fp, fn, tn):
    precision = tp / (tp + fp + 1e-8)
    recall = tp / (tp + fn + 1e-8)
    f1 = 2.0 * precision * recall / (precision + recall + 1e-8)
    iou = tp / (tp + fp + fn + 1e-8)
    dice = 2.0 * tp / (2.0 * tp + fp + fn + 1e-8)
    accuracy = (tp + tn) / (tp + tn + fp + fn + 1e-8)
    return {"precision": precision, "recall": recall, "f1": f1, "iou": iou, "dice": dice, "accuracy": accuracy}


def compute_counts_from_logits(logits, targets, valid, threshold):
    probs = torch.sigmoid(logits)
    preds = (probs >= threshold).float()
    preds = preds[valid == 1]
    targets = targets[valid == 1]
    tp = int(((preds == 1) & (targets == 1)).sum().item())
    fp = int(((preds == 1) & (targets == 0)).sum().item())
    fn = int(((preds == 0) & (targets == 1)).sum().item())
    tn = int(((preds == 0) & (targets == 0)).sum().item())
    return tp, fp, fn, tn


def evaluate_model(model, loader, criterion, threshold=0.5, desc=None):
    model.eval()
    total_loss, total_tp, total_fp, total_fn, total_tn = 0.0, 0, 0, 0, 0
    desc = desc or f"Evaluating th={threshold:.3f}"
    with torch.no_grad():
        for images, targets, valid in tqdm(loader, desc=desc, leave=False):
            images = images.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)
            valid = valid.to(device, non_blocking=True)
            with torch.autocast(device_type=device.type, dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
                logits = model(images)
                loss = criterion(logits, targets, valid)
            total_loss += float(loss.item())
            tp, fp, fn, tn = compute_counts_from_logits(logits, targets, valid, threshold=threshold)
            total_tp += tp; total_fp += fp; total_fn += fn; total_tn += tn
    metrics = counts_to_metrics(total_tp, total_fp, total_fn, total_tn)
    metrics.update({"loss": total_loss / max(len(loader), 1), "tp": total_tp, "fp": total_fp, "fn": total_fn, "tn": total_tn, "threshold": threshold})
    return metrics


def validation_threshold_sweep(model, loader, criterion):
    model.eval()
    bin_edges = np.linspace(0.0, 1.0, 1001)
    pos_hist = np.zeros(1000, dtype=np.float64)
    neg_hist = np.zeros(1000, dtype=np.float64)
    total_loss = 0.0

    with torch.no_grad():
        for images, targets, valid in tqdm(loader, desc="Validation probability histograms"):
            images = images.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)
            valid = valid.to(device, non_blocking=True)
            with torch.autocast(device_type=device.type, dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
                logits = model(images)
                loss = criterion(logits, targets, valid)
            total_loss += float(loss.item())
            probs = torch.sigmoid(logits).detach().float().cpu().numpy()
            targets_np = targets.detach().cpu().numpy()
            valid_np = valid.detach().cpu().numpy()
            valid_pixels = valid_np == 1
            probs_valid = probs[valid_pixels]
            targets_valid = targets_np[valid_pixels]
            if probs_valid.size == 0:
                continue
            pos_probs = probs_valid[targets_valid == 1]
            neg_probs = probs_valid[targets_valid == 0]
            if pos_probs.size > 0:
                pos_hist += np.histogram(pos_probs, bins=bin_edges)[0]
            if neg_probs.size > 0:
                neg_hist += np.histogram(neg_probs, bins=bin_edges)[0]

    pos_cum_high = np.cumsum(pos_hist[::-1])[::-1]
    neg_cum_high = np.cumsum(neg_hist[::-1])[::-1]
    total_pos = pos_hist.sum()
    total_neg = neg_hist.sum()
    thresholds = np.round(np.arange(THRESHOLD_MIN, THRESHOLD_MAX + 0.5 * THRESHOLD_STEP, THRESHOLD_STEP), 3)
    rows = []
    for th in thresholds:
        bin_idx = int(np.floor(th * 1000.0))
        bin_idx = max(0, min(bin_idx, 999))
        tp = pos_cum_high[bin_idx]
        fp = neg_cum_high[bin_idx]
        fn = total_pos - tp
        tn = total_neg - fp
        metrics = counts_to_metrics(tp, fp, fn, tn)
        rows.append({
            "threshold": float(th),
            "loss": total_loss / max(len(loader), 1),
            "tp": int(tp), "fp": int(fp), "fn": int(fn), "tn": int(tn),
            "precision": metrics["precision"], "recall": metrics["recall"],
            "f1": metrics["f1"], "iou": metrics["iou"], "dice": metrics["dice"], "accuracy": metrics["accuracy"],
        })
    sweep_df = pd.DataFrame(rows)
    sweep_df.to_csv(VAL_THRESHOLD_CSV, index=False)
    best = sweep_df.loc[sweep_df["iou"].idxmax()].to_dict()
    print(f"Validation threshold sweep saved to: {VAL_THRESHOLD_CSV}")
    print(f"Best validation threshold: {best['threshold']:.3f} | IoU={best['iou']:.4f} | Dice={best['dice']:.4f} | Precision={best['precision']:.4f} | Recall={best['recall']:.4f}")
    return sweep_df, float(best["threshold"])

# ============================================================
# 8. TRAINING
# ============================================================

def train_model(model, train_loader, val_loader, criterion, train_mean, train_std):
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scaler = torch.cuda.amp.GradScaler(enabled=(USE_AMP and device.type == "cuda"))
    best_val_iou, best_epoch = 0.0, 0
    history = []

    for epoch in range(NUM_EPOCHS):
        model.train()
        train_loss = 0.0
        for images, targets, valid in tqdm(train_loader, desc=f"Epoch {epoch + 1}/{NUM_EPOCHS}"):
            images = images.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)
            valid = valid.to(device, non_blocking=True)
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type=device.type, dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
                logits = model(images)
                loss = criterion(logits, targets, valid)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            train_loss += float(loss.item())
        train_loss /= max(len(train_loader), 1)

        val_metrics = evaluate_model(model, val_loader, criterion, threshold=0.5, desc="Validation @0.5")
        row = {
            "epoch": epoch + 1, "train_loss": train_loss, "val_loss": val_metrics["loss"],
            "val_precision": val_metrics["precision"], "val_recall": val_metrics["recall"],
            "val_f1": val_metrics["f1"], "val_iou": val_metrics["iou"], "val_dice": val_metrics["dice"],
            "learning_rate": optimizer.param_groups[0]["lr"],
        }
        history.append(row)
        pd.DataFrame(history).to_csv(HISTORY_CSV, index=False)
        print(f"Epoch [{epoch + 1:03d}/{NUM_EPOCHS}] | T.Loss={train_loss:.4f} | V.Loss={val_metrics['loss']:.4f} | IoU={val_metrics['iou']:.4f} | Dice={val_metrics['dice']:.4f} | Prec={val_metrics['precision']:.4f} | Rec={val_metrics['recall']:.4f}")

        if val_metrics["iou"] > best_val_iou:
            best_val_iou = val_metrics["iou"]
            best_epoch = epoch + 1
            torch.save({
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "epoch": best_epoch,
                "best_val_iou_at_05": best_val_iou,
                "base_channels": BASE_CHANNELS,
                "patch_h": PATCH_H,
                "patch_w": PATCH_W,
                "stride": STRIDE,
                "pos_weight": POS_WEIGHT,
                "learning_rate": LEARNING_RATE,
                "mean": train_mean.tolist(),
                "std": train_std.tolist(),
                "years": YEARS,
                "split": {"train": TRAIN_FRAC, "val": VAL_FRAC, "test": TEST_FRAC},
            }, BEST_MODEL_PATH)
            print(f"-> New best model saved: epoch={best_epoch}, val IoU@0.5={best_val_iou:.4f}")

    print(f"Training completed. Best epoch: {best_epoch}, best val IoU@0.5: {best_val_iou:.4f}")
    print(f"Best model saved to: {BEST_MODEL_PATH}")
    return pd.DataFrame(history)

# ============================================================
# 9. VISUALIZATION
# ============================================================

def predict_single_patch(model, row, mean, std):
    rgb, mask = load_preprocessed_pair_cached(row["image_path"], row["mask_path"])
    x0, y0, x1, y1 = int(row["x0"]), int(row["y0"]), int(row["x1"]), int(row["y1"])
    img_patch = rgb[y0:y1, x0:x1].astype(np.float32) / 255.0
    mask_patch = mask[y0:y1, x0:x1].astype(np.uint8)
    target = (mask_patch == 1).astype(np.uint8)
    valid = (mask_patch != 2).astype(np.uint8)
    img_norm = (img_patch - mean) / (std + 1e-8)
    img_norm = np.transpose(img_norm, (2, 0, 1))
    x = torch.tensor(img_norm[None, :, :, :], dtype=torch.float32).to(device)
    model.eval()
    with torch.no_grad():
        with torch.autocast(device_type=device.type, dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
            logits = model(x)
            probs = torch.sigmoid(logits)
    prob_map = probs.squeeze().detach().float().cpu().numpy()
    return img_patch, target, valid, prob_map


def plot_confusion_matrix(metrics: dict):
    cm = np.array([[metrics["tn"], metrics["fp"]], [metrics["fn"], metrics["tp"]]], dtype=np.int64)
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cm)
    ax.set_title(f"Test Confusion Matrix\nThreshold={metrics['threshold']:.3f} | IoU={metrics['iou']:.4f} | Dice={metrics['dice']:.4f}")
    ax.set_xticks([0, 1]); ax.set_yticks([0, 1])
    ax.set_xticklabels(["Pred no storm", "Pred storm"])
    ax.set_yticklabels(["True no storm", "True storm"])
    ax.set_xlabel("Predicted"); ax.set_ylabel("Ground truth")
    for i in range(2):
        for j in range(2):
            ax.text(j, i, f"{cm[i, j]:,}", ha="center", va="center")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(CONFUSION_MATRIX_FIG, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Confusion matrix figure saved to: {CONFUSION_MATRIX_FIG}")


def plot_test_examples(model, test_inv, mean, std, threshold):
    positive = test_inv[test_inv["positive_patch"]].copy()
    if len(positive) >= N_TEST_VISUALIZATIONS:
        selected = positive.sort_values("storm_ratio_valid", ascending=False).head(N_TEST_VISUALIZATIONS).reset_index(drop=True)
    else:
        selected = test_inv.sample(n=min(N_TEST_VISUALIZATIONS, len(test_inv)), random_state=SEED).reset_index(drop=True)

    n = len(selected)
    fig, axes = plt.subplots(nrows=n, ncols=3, figsize=(13, 4.2 * n))
    if n == 1:
        axes = np.expand_dims(axes, axis=0)

    for i, (_, row) in enumerate(selected.iterrows()):
        img_patch, target, valid, prob_map = predict_single_patch(model, row, mean, std)
        pred = (prob_map >= threshold).astype(np.uint8)
        pred[valid == 0] = 0
        gt_display = target.copy(); gt_display[valid == 0] = 2
        pred_display = pred.copy(); pred_display[valid == 0] = 2

        axes[i, 0].imshow(img_patch)
        axes[i, 0].set_title(f"Original patch\n{row['year']} | {row['day_key']}\nstorm={row['storm_ratio_valid']:.2%}")
        axes[i, 0].axis("off")
        axes[i, 1].imshow(gt_display, vmin=0, vmax=2)
        axes[i, 1].set_title("Ground-truth mask")
        axes[i, 1].axis("off")
        axes[i, 2].imshow(pred_display, vmin=0, vmax=2)
        axes[i, 2].set_title(f"Prediction\nthreshold={threshold:.3f}")
        axes[i, 2].axis("off")

    fig.tight_layout()
    fig.savefig(TEST_VIS_FIG, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Test visualization saved to: {TEST_VIS_FIG}")

# ============================================================
# 10. MAIN
# ============================================================

if __name__ == "__main__":
    print("============================================================")
    print("CBAM U-Net MDGM/MDAD article-style training")
    print("============================================================")
    print(f"Root folder: {ROOT_DIR}")
    print(f"Years: {YEARS}")

    records_by_year = {year: load_year_records(year) for year in YEARS}
    split_df = split_records_per_year(records_by_year)
    train_image_df = split_df[split_df["split"] == "train"].reset_index(drop=True)

    print("Computing normalization from training images only...")
    train_mean, train_std = compute_train_mean_std(train_image_df)
    print(f"Train mean: {train_mean}")
    print(f"Train std : {train_std}")

    print("Building article-style patch inventory...")
    patch_inv = build_patch_inventory(split_df)
    train_inv = patch_inv[patch_inv["split"] == "train"].reset_index(drop=True)
    val_inv = patch_inv[patch_inv["split"] == "val"].reset_index(drop=True)
    test_inv = patch_inv[patch_inv["split"] == "test"].reset_index(drop=True)
    print(f"Train patches: {len(train_inv)}")
    print(f"Val patches  : {len(val_inv)}")
    print(f"Test patches : {len(test_inv)}")

    train_dataset = MDGMPatchDataset(train_inv, mean=train_mean, std=train_std, augment_4x=True)
    val_dataset = MDGMPatchDataset(val_inv, mean=train_mean, std=train_std, augment_4x=False)
    test_dataset = MDGMPatchDataset(test_inv, mean=train_mean, std=train_std, augment_4x=False)

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=(device.type == "cuda"), persistent_workers=(NUM_WORKERS > 0))
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=(device.type == "cuda"), persistent_workers=(NUM_WORKERS > 0))
    test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=(device.type == "cuda"), persistent_workers=(NUM_WORKERS > 0))

    model = CBAMUNet(in_channels=3, out_channels=1, base_channels=BASE_CHANNELS).to(device)
    criterion = MaskedWeightedBCELoss(pos_weight=POS_WEIGHT).to(device)

    print("Starting training...")
    _ = train_model(model, train_loader, val_loader, criterion, train_mean, train_std)

    print("Loading best model for threshold selection and final test...")
    checkpoint = torch.load(BEST_MODEL_PATH, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    print("Selecting threshold from validation set...")
    _, best_threshold = validation_threshold_sweep(model, val_loader, criterion)

    print("Evaluating final test set...")
    test_metrics = evaluate_model(model, test_loader, criterion, threshold=best_threshold, desc="Final test")
    pd.DataFrame([test_metrics]).to_csv(TEST_METRICS_CSV, index=False)

    print("\n============== FINAL TEST RESULTS =============")
    print(f"Threshold : {test_metrics['threshold']:.3f}")
    print(f"Loss      : {test_metrics['loss']:.4f}")
    print(f"Accuracy  : {test_metrics['accuracy']:.4f}")
    print(f"Precision : {test_metrics['precision']:.4f}")
    print(f"Recall    : {test_metrics['recall']:.4f}")
    print(f"F1-score  : {test_metrics['f1']:.4f}")
    print(f"IoU       : {test_metrics['iou']:.4f}")
    print(f"Dice      : {test_metrics['dice']:.4f}")
    print(f"TP        : {test_metrics['tp']}")
    print(f"FP        : {test_metrics['fp']}")
    print(f"FN        : {test_metrics['fn']}")
    print(f"TN        : {test_metrics['tn']}")
    print(f"Test metrics saved to: {TEST_METRICS_CSV}")

    print("Generating final figures...")
    plot_confusion_matrix(test_metrics)
    plot_test_examples(model, test_inv, mean=train_mean, std=train_std, threshold=best_threshold)

    print("Completed.")
    print(f"All outputs saved in: {OUTPUT_DIR}")
